server:
  port: 9114

spring:
  application:
    name: demo-kstream
  output:
    ansi:
      enabled: always
  kafka:
    streams:
      application-id: enhanced_consumer
      client-id: group-dev-local-01
      consumer-id: "-"
      bootstrap-servers: 127.0.0.1:9092
#    consumer:
#      group-id: group-dev-local-01
custom:
  topics:
    input: client_insight
    output: sms_notification
    retry: client_insight_retry
    error: client_insight_error
